all: main

main: wersja1.c wersja2.c wersja3.c
	gcc -Wall wersja1.c -o wersja1 -lpthread
	gcc -Wall wersja2.c -o wersja2 -lpthread
	gcc -Wall wersja3.c -o wersja3 -lpthread

clean:
	rm wersja1 wersja2 wersja3
